In [35]:
import numpy as np

In [36]:
def generate_time_series(batch_size, n_steps):
    freq1, freq2, offsets1, offsets2 = np.random.rand(4, batch_size, 1)
    time = np.linspace(0, 1, n_steps)
    series = 0.5 * np.sin((time - offsets1) * (freq1 * 10 + 10))  #   웨이브 1
    series += 0.2 * np.sin((time - offsets2) * (freq2 * 20 + 20)) # + 웨이브 2
    series += 0.1 * (np.random.rand(batch_size, n_steps) - 0.5)   # + 잡음
    return series[..., np.newaxis].astype(np.float32)

batch_size 개수만큼의 시계열 데이터가 생성

각 시계열 데이터는 n_steps 만큼의 데이터가 있고,

앞선 n_steps - 1 개의 데이터를 통해 n_steps 번째의 데이터를 예측한다.

In [37]:
np.random.seed(42)

n_steps = 50
series = generate_time_series(10000, n_steps + 1)
X_train, y_train = series[:7000, :n_steps], series[:7000, -1]
X_valid, y_valid = series[7000:9000, :n_steps], series[7000:9000, -1]
X_test, y_test = series[9000:, :n_steps], series[9000:, -1]

In [38]:
X_train.shape

(7000, 50, 1)

In [39]:
X_train[0].shape

(50, 1)

In [40]:
y_train.shape

(7000, 1)

In [41]:
# 활성화 함수
class activation_function:
  # 시그모이드 함수
  def sigmoid(self, x):
    return 1 / (1+np.e**-x)
  
  # 시그모이드 함수의 미분 함수
  def sigmoid_diff(self, x):
    return x * (1 - x)

In [42]:
# 비용 함수 클래스, 비용 함수의 종류에 따라 다른 클래스 내 함수를 사용한다.
class cost_function:
  # 예측값
  predict = []
  # 타겟값
  target = []
  # 비용 함수값
  error_cost = []

  # 오차 제곱합
  def errer_squared_sum(self, predict, target):
    self.predict = predict
    self.target = target

    self.error_cost = np.sum(0.5*((predict - target)**2))
    return self.error_cost

  # 오차 제곱합 미분 함수
  def diff_error_squared_sum(self):
    return self.predict - self.target

In [413]:
class RNN_vector_to_sequence:
    #입력값
    input_data = []
    
    #가중치
    weight = []
    
    #편향값
    bias = []

    # 입력 가중치
    input_w = []

    # 이전 출력에 대한 가중치
    before_w = []

    # 출력 가중치
    result_w = []

    # 편향 값 bais
    bias = []

    # 노드 입력
    node_input = []

    # 노드 출력
    node_output = []

    # 타겟, 목푯값
    target = []

    # 활성화 함수
    activation = activation_function()

    # 비용 함수
    cost = cost_function()

    # 예측 결과
    predict = []

    # 각 층의 델타 값의 저장
    delta = []

     # 각 가중치 업데이트 크기
    input_weight_update = []

    before_weight_update = []

    result_weight_update = []

    def delta_to_sequence_cal_rnn(self, input, target):

      # 타겟값의 저장
      self.target = target


      # 입력 데이터 크기에 맞는 가중치 값이 생성되어야 한다.
      # 입력 (3,1) 데이터에 대한 연산 결과 (1,1)를 예측한다고 가정,

      # 입력값에 사용되는 가중치
      # (3,1) 크기의 입력 데이터에 대해 (1,1) 의 행렬곱 연산 결과를 얻기 위해, (1,3) 크기의 가중치 행렬이 필요하다
      input_w = np.random.rand(target.shape[0], input.shape[0])

      # 이전 출력에 대한 가중치
      # (1,1) 노드 출력에 대해 (1,1) 의 행렬곱 연산 결과를 얻기 위한, (1,1) 크기의 가중치 행렬
      before_w = np.random.rand(target.shape[0], target.shape[0])

      # 예측에 사용되는 가중치
      # 노드 출력 (3,1) 에 대해 예측값 (1,1) 크기의 데이터 행렬을 얻기 위해, (1,3) 크기의 가중치 행렬이 필요하다.
      result_w = np.random.rand(target.shape[0], input.shape[0])

      # 이전 노드의 출력, 첫 부분의 경우 이 값이 0이다. 행렬의 크기는 (1,1)
      before = np.zeros((target.shape[0], target.shape[0]))

      # (3, n) 크기의 입력 데이터에서 n 번의 반복을 수행하게 됨
      for i in range(input.shape[0]):
        # 노드 입력 계산
        node_input = (before_w @ before) + (input_w @ input)
        self.node_input.append(node_input)

        # 노드 출력 계산
        node_output = self.activation.sigmoid(node_input)
        self.node_output.append(node_output)

        # 순환 노드의 다음 노드 입력값의 계산
        before = self.before_w @ node_output

      self.predict = self.result_w @ node_output

      return self.predict

    def delta_to_sequence_cal_rnn_test(self, input, target):

      # 타겟값의 저장
      self.target = target

      # 입력 데이터의 저장
      self.input = input

      # 입력 데이터 크기에 맞는 가중치 값이 생성되어야 한다.
      # 입력 (3,1) 데이터에 대한 연산 결과 (1,1)를 예측한다고 가정,

      # 입력값에 사용되는 가중치
      # (3,1) 크기의 입력 데이터에 대해 (1,1) 의 행렬곱 연산 결과를 얻기 위해, (1,3) 크기의 가중치 행렬이 필요하다
      self.input_w = np.random.rand(target.shape[0], input.shape[1])
      
      # 이전 출력에 대한 가중치
      # (1,1) 노드 출력에 대해 (1,1) 의 행렬곱 연산 결과를 얻기 위한, (1,1) 크기의 가중치 행렬
      self.before_w = np.random.rand(target.shape[0], target.shape[0])

      # 예측에 사용되는 가중치
      # 노드 출력 (3,1) 에 대해 예측값 (1,1) 크기의 데이터 행렬을 얻기 위해, (1,3) 크기의 가중치 행렬이 필요하다.
      self.result_w = np.random.rand(target.shape[0], input.shape[1])

      # 이전 노드의 출력, 첫 부분의 경우 이 값이 0이다. 행렬의 크기는 (1,1)
      before = np.zeros((target.shape[0], target.shape[0]))
      
      # (3, n) 크기의 입력 데이터에서 n 번의 반복을 수행하게 됨
      for i in range(input.shape[0]):
        # 노드 입력 데이터의 numpy 행렬 생성
        input_data = input[i].reshape(input.shape[1],-1)

        # RNN 노드 입력 값 계산, 이전 노드 출력 @ 가중치 + 입력 데이터 @ 가중치
        node_input = (self.before_w @ before) + (self.input_w @ input_data)
        self.node_input.append(node_input)

        # 노드 출력 계산, 활성화 함수 연산을 수행한다.
        node_output = self.activation.sigmoid(node_input)
        self.node_output.append(node_output)

        # 순환 노드의 다음 노드 입력값의 계산
        before = self.before_w @ node_output

      self.predict = self.activation.sigmoid(self.result_w @ node_output)

      return self.predict

    def cost_cal(self):
      return self.cost.errer_squared_sum(self.predict, self.target)

    
    def cal_delta(self):
      #출력 노드의 변화량에 대한 오차 함수의 변화량 계산
      delta = (self.cost.diff_error_squared_sum() * self.activation.sigmoid_diff(self.predict))
      self.delta.append(delta)

      # 해당 delta 값을 통해 result_w 의 가중치 업데이트 크기를 계산할 수 있다.
      # delta 값과 result_w 의 변화량(이전 노드의 출력) 의 계산을 통해 result_w 의 변화량을 계산한다.
      self.result_weight_update = (delta @ self.node_output[self.input.shape[0] - 1].T).T

      # 노드 출력의 변화에 대한 비용 함수의 변화량 계산
      delta = self.result_w @ delta
      # 활성화 함수에 따른 변화량 계산, 해당 값이 노드 변화에 대한 비용 함수의 변화량이 된다. 
      delta = delta * self.activation.sigmoid_diff(self.node_output[self.input.shape[0] - 1])
      # 노드별 delta 값의 저장
      self.delta.append(delta)

      # 출력층과 연결된 노드를 제외한 n-1 개의 delta 값을 계산하기 위해 각 반복은 n-1 번 만큼 반복되어야 한다.
      for i in range(input.shape[0] - 2, -1, -1):
        delta = self.before_w @ delta
        delta = delta * self.activation.sigmoid_diff(self.node_output[i])
        self.delta.append(delta)
      
      # 반복이 종료된 후 최초 노드의 변화량에 대한 비용 함수의 변화량을 얻을 수 있다.
      # 각 가중치 변화량의 계산
      self.input_weight_update = (delta @ self.input[0])

      # before_weight 의 변화량은 최초 입력이 0 으로 정의했기 때문에 최초 노드의 출력을 이용해 그 변화량을 계산한다.
      self.before_weight_update = (delta @ self.node_output[0])

    def update_weight(self, learning_rate):
      self.input_w = self.input_w - self.input_weight_update * learning_rate
      self.before_w = self.before_w - self.before_weight_update * learning_rate
      self.result_w = self.result_w - self.result_weight_update * learning_rate

    def iterations(self, iterations, learning_rate):
      for j in range(iterations):
        # 이전 노드의 출력, 첫 부분의 경우 이 값이 0이다. 행렬의 크기는 (1,1)
        before = np.zeros((target.shape[0], target.shape[0]))
        for i in range(input.shape[0]):
          # 노드 입력 데이터의 numpy 행렬 생성
          input_data = input[i].reshape(input.shape[1],-1)

          # RNN 노드 입력 값 계산, 이전 노드 출력 @ 가중치 + 입력 데이터 @ 가중치
          node_input = (self.before_w @ before) + (self.input_w @ input_data)
          self.node_input.append(node_input)

          # 노드 출력 계산, 활성화 함수 연산을 수행한다.
          node_output = self.activation.sigmoid(node_input)
          self.node_output.append(node_output)

          # 순환 노드의 다음 노드 입력값의 계산
          before = self.before_w @ node_output

        self.predict = self.activation.sigmoid(self.result_w @ node_output)
        self.cal_delta()
        self.update_weight(learning_rate)
        print(self.cost_cal())



In [414]:
rnn = RNN_vector_to_sequence()

In [415]:
input = X_train[0]

In [416]:
target = y_train[0].reshape(1,-1)

In [417]:
input.shape

(50, 1)

In [418]:
target.shape

(1, 1)

In [419]:
rnn.delta_to_sequence_cal_rnn_test(input, target)

array([[0.58774118]])

In [420]:
rnn.cost_cal()

0.4442805211918948

In [421]:
rnn.cal_delta()

In [422]:
rnn.input_weight_update

array([2.23665987e-91])

In [423]:
rnn.before_weight_update

array([[2.7944446e-91]])

In [424]:
rnn.result_weight_update

array([[0.10841863]])

In [425]:
rnn.iterations(10, 0.001)

0.4442805211918948
0.4442687666180695
0.4442570119874555
0.4442452574555864
0.4442335030225001
0.44422174868823233
0.4442099944528192
0.4441982403162963
0.44418648627869967
0.44417473234006505


In [426]:
rnn.iterations(10, 0.01)

0.44416297850042835
0.4440454433259426
0.44392790408561916
0.4438103748104592
0.4436928555381432
0.44357534630448625
0.4434578471452886
0.4433403580963358
0.443222879193399
0.44310541047223456


In [427]:
rnn.iterations(100, 0.01)

0.44298795196858454
0.4428705037181756
0.44275306575672035
0.4426356381199159
0.44251822084344483
0.44240081396297454
0.44228341751415745
0.44216603153263095
0.4420486560540172
0.44193129111392304
0.4418139367479403
0.44169659299164504
0.4415792598805985
0.4414619374503459
0.4413446257364176
0.4412273247743275
0.44111003459957476
0.44099275524764237
0.4408754867539975
0.44075822915409185
0.4406409824833612
0.44052374677722517
0.4404065220710877
0.44028930840033637
0.44017210580034277
0.44005491430646276
0.43993773395403524
0.43982056477838344
0.4397034068148142
0.43958626009861773
0.43946912466506777
0.43935200054942203
0.43923488778692105
0.4391177864127893
0.4390006964622342
0.4388836179704468
0.43876655097260087
0.43864949550385374
0.43853245159934584
0.43841541929420047
0.4382983986235238
0.43818138962240555
0.43806439232591743
0.43794740676911487
0.4378304329870352
0.4377134710146992
0.4375965208871099
0.4374795826392528
0.4373626563060963
0.4372457419225912
0.43712883952367054
0.

In [428]:
target

array([[-0.35489398]], dtype=float32)

In [429]:
rnn.predict

array([[0.57399355]])