In [1]:
import numpy as np
import sympy

In [2]:
perch_length = np.array(
    [8.4, 13.7, 15.0, 16.2, 17.4, 18.0, 18.7, 19.0, 19.6, 20.0, 
     21.0, 21.0, 21.0, 21.3, 22.0, 22.0, 22.0, 22.0, 22.0, 22.5, 
     22.5, 22.7, 23.0, 23.5, 24.0, 24.0, 24.6, 25.0, 25.6, 26.5, 
     27.3, 27.5, 27.5, 27.5, 28.0, 28.7, 30.0, 32.8, 34.5, 35.0, 
     36.5, 36.0, 37.0, 37.0, 39.0, 39.0, 39.0, 40.0, 40.0, 40.0, 
     40.0, 42.0, 43.0, 43.0, 43.5, 44.0]
     )
perch_weight = np.array(
    [5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 
     110.0, 115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 
     130.0, 150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 
     197.0, 218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 
     514.0, 556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 
     820.0, 850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 
     1000.0, 1000.0]
     )

In [3]:
class Rnn:
  """
  순환 신경망의 계산
  """
  # 입력 가중치
  input_w = []

  # 이전 출력에 대한 가중치
  before_w = []

  # 출력 가중치
  result_w = []

  # 편향 값 bais
  bias = []

  def cal_rnn(self, input, output, input_w = [], bias = []):
    """
    순환 신경망 은닉층까지의 계산
    args
      input : 입력 데이터
      output : 원하는 출력 형태
    return 
      순환 신경망의 계산 결과
    """
    # 이전 출력에 대한 입력, 첫 부분의 경우 이 값이 0이다.
    before = np.zeros((output.shape[0], output.shape[1]))

    # 이전 출력에 대한 가중치
    before_w = np.random.rand(output.shape[0], output.shape[0])

    self.before_w.append(before_w)

    # 가중치 w의 생성, 
    if not input_w:
      input_w = np.random.rand(output.shape[0], input.shape[0])
    
    if not bias:
      bias = np.random.rand()

    self.input_w.append(input_w)

    self.bias.append(bias)

    return (before_w @ before) + (input_w @ input) + bias

  def cal_result(self, input, output, w = []):
    """
    순환 신경망의 은닉층 출력에서 최종 결과값으로의 계산
    args
      input : 입력 데이터
      output : 원하는 출력 형태
    return 
      행렬 곱 연산 결과
    """
    # 가중치 생성
    if not w:
      result_w = np.random.rand(output.shape[0], output.shape[0])

    self.result_w.append(result_w)

    return result_w @ input

In [4]:
class Activation:
  """
  데이터의 활성화 함수 연산 결과를 얻기 위함
  추가로 역전파 계산에 필요한 활성화 함수의 미분 함수
  """
  # 활성화 함수
  fx = 0
  # 활성화 함수의 미분 함수
  d_fx = 0

  def sigmoid_fun(self, input):
    """
    시그모이드 함수
    자연 상수의 지수 함수를 사용한 0~1 사이의 값 출력
    Args:
      input : 입력값
    Return:
      0~1 사이의 값
    """
    x = sympy.Symbol('x')
    result = []

    self.fx = 1/(1+np.e**(-x))

    self.d_fx = sympy.diff(self.fx, x)

    for i in range(input.shape[0]):
      result.append(self.fx.subs([(x, input[i][0])]))

    return np.array(result).reshape(-1, 1)

  def d_sigmoid_fun(self, input):
    """
    시그모이드 함수의 미분값, 노드의 출력이 입력된다.
    arg
      input : 입력값
    return
      시그모이드 미분 함수의 계산 값
    """
    result = []

    x = sympy.Symbol('x')

    for i in range(input.shape[0]):
      result.append(self.d_fx.subs([(x,input[i][0])]))

    return np.array(result).reshape(-1, 1)

In [5]:
class Error:
  """
  오차 함수와 오차 함수의 미분 함수를 얻을 수 있다.  
  """
  # 오차 함수
  fx = 0
  
  # 오차 함수의 미분값
  d_fx = 0
  
  def RMSE(self, target, predict):
    """
    일반적인 제곱 오차 함수
    args:
      target : 목표 변수
      predict : 예측 변수
    return:
      제곱 오차 평균 값
    """
    result = (predict - target)**2
    self.result = np.mean(result)

    t = sympy.Symbol('t')
    y = sympy.Symbol('y')

    self.fx = 1/2*((y-t)**2)

    self.d_fx = sympy.diff(self.fx, y)

    return self.result

  def d_RMSE(self, target, predict):
    """
    RMSE 의 미분 함수
    args
      target : 목표 변수
      predict : 예측 변수
    return:
      미분 함수의 계산 값
    """
    result = []

    t = sympy.Symbol('t')
    y = sympy.Symbol('y')

    for i in range(target.shape[0]):
      result.append(self.d_fx.subs([(t, target[i][0]), (y, predict[i][0])]))
    
    return np.array(result).reshape(-1, 1)


In [6]:
input = perch_length[:3].reshape(-1,1)

In [7]:
target = perch_length[:4].reshape(-1,1)

In [8]:
output = np.zeros((4,1))

In [9]:
input.shape

(3, 1)

In [10]:
output.shape

(4, 1)

In [11]:
rnn = Rnn()

In [12]:
rnn_hidden_input = rnn.cal_rnn(input, output)
rnn_hidden_input

array([[21.46257151],
       [ 6.61627868],
       [21.23432189],
       [11.53058143]])

In [13]:
act = Activation()

In [14]:
rnn_hidden_output = act.sigmoid_fun(rnn_hidden_input)
rnn_hidden_output

array([[0.999999999522555],
       [0.998663386609177],
       [0.999999999400138],
       [0.999990175106608]], dtype=object)

In [15]:
rnn_result = rnn.cal_result(rnn_hidden_output, output)
rnn_result

array([[2.84689331637997],
       [2.70974152330071],
       [2.68039647743849],
       [2.18784342340687]], dtype=object)

델타 연산

예측 노드의 델타,

오차 함수의 미분값과 동일하다.(활성화 함수로 항등 함수를 사용했기 때문)

In [16]:
err = Error()

In [17]:
result = err.RMSE(target, rnn_result)
result

124.933984526100

In [18]:
result_delta = err.d_RMSE(target, rnn_result)
result_delta

array([[-5.55310668362003],
       [-10.9902584766993],
       [-12.3196035225615],
       [-14.0121565765931]], dtype=object)

예측 노드의 델타를 사용한 result_w 값 업데이트

In [19]:
rnn_hidden_output

array([[0.999999999522555],
       [0.998663386609177],
       [0.999999999400138],
       [0.999990175106608]], dtype=object)

In [20]:
d_result_w = result_delta * rnn_hidden_output
d_result_w

array([[-5.55310668096873],
       [-10.9755687500507],
       [-12.3196035151714],
       [-14.0120189086486]], dtype=object)

예측 노드의 델타를 이용한 은닉층 노드의 delta 값 계산

In [21]:
result_delta

array([[-5.55310668362003],
       [-10.9902584766993],
       [-12.3196035225615],
       [-14.0121565765931]], dtype=object)

In [22]:
rnn.result_w[0]

array([[0.81713877, 0.93089604, 0.63919138, 0.46091591],
       [0.74921658, 0.2477459 , 0.79755247, 0.91556672],
       [0.68822126, 0.91101182, 0.47870144, 0.60368555],
       [0.665497  , 0.35016595, 0.94890992, 0.22374079]])

은닉층의 각 노드들의 변화에 따른 오차 함수의 변화량

In [23]:
d_hidden_c = (result_delta.T @ rnn.result_w[0]).T
d_hidden_c

array([[-30.5754037727538],
       [-24.0220411261332],
       [-31.5084920120859],
       [-23.1940877318311]], dtype=object)

위 값을 통한 은닉층 각 노드들의 델타 계산, 활성화 함수의 미분값과의 계산

In [24]:
d_hidden_c

array([[-30.5754037727538],
       [-24.0220411261332],
       [-31.5084920120859],
       [-23.1940877318311]], dtype=object)

In [25]:
act.d_sigmoid_fun(rnn_hidden_output)

array([[0.196611933284861],
       [0.196733343319322],
       [0.196611933295984],
       [0.196612825907462]], dtype=object)

In [26]:
hidden_delta = d_hidden_c * act.d_sigmoid_fun(rnn_hidden_output)
hidden_delta

array([[-6.01148924672637],
       [-4.72593646409843],
       [-6.19494552973728],
       [-4.56025513330089]], dtype=object)

은닉층의 델타값을 통한 input_w 의 계산

In [27]:
hidden_delta

array([[-6.01148924672637],
       [-4.72593646409843],
       [-6.19494552973728],
       [-4.56025513330089]], dtype=object)

In [33]:
input

array([[ 8.4],
       [13.7],
       [15. ]])

In [37]:
rnn.input_w[0]

array([[0.58045673, 0.20412148, 0.85915605],
       [0.00226394, 0.35454499, 0.05580436],
       [0.31899667, 0.88823762, 0.36553097],
       [0.47915032, 0.2421538 , 0.21901878]])

In [38]:
d_input_w = hidden_delta * input.T
d_input_w

array([[-50.4965096725015, -82.3574026801513, -90.1723387008956],
       [-39.6978662984268, -64.7453295581485, -70.8890469614765],
       [-52.0375424497931, -84.8707537574007, -92.9241829460591],
       [-38.3061431197275, -62.4754953262223, -68.4038269995134]],
      dtype=object)

은닉층의 델타값을 통한 before_w 의 계산

In [39]:
hidden_delta

array([[-6.01148924672637],
       [-4.72593646409843],
       [-6.19494552973728],
       [-4.56025513330089]], dtype=object)

In [40]:
output

array([[0.],
       [0.],
       [0.],
       [0.]])

In [31]:
rnn.before_w[0]

array([[0.67443854, 0.04859   , 0.37792503, 0.60971927],
       [0.68256154, 0.37249555, 0.54094653, 0.38607249],
       [0.0830565 , 0.94813373, 0.64650067, 0.99249619],
       [0.6808205 , 0.53670434, 0.88575993, 0.66067123]])

In [41]:
d_before_w = hidden_delta * output.T
d_before_w

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=object)